# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AuthApp

  # minimum platform version 
  platform :ios, '9.0'
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  # firebase Authentication
  pod 'Firebase/Auth', '~> 5.20.1'
  # Then run $ >> pod update

  
  target 'AuthAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AuthApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AuthApp-tvOS

  target 'AuthApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
